export const nowService = [
  // =========================
  // Instagram (ig)
  // =========================
  { country: "United States", countryId: "187", service: "ig" },
  { country: "Colombia", countryId: "33", service: "ig" },
  { country: "France", countryId: "78", service: "ig" },
  { country: "United Kingdom", countryId: "16", service: "ig" },
  { country: "Indonesia", countryId: "6", service: "ig" },
  { country: "Thailand", countryId: "52", service: "ig" },
  { country: "Brazil", countryId: "73", service: "ig" },
  { country: "Ukraine", countryId: "1", service: "ig" },
  { country: "Germany", countryId: "43", service: "ig" },
  { country: "Canada", countryId: "36", service: "ig" },
  { country: "Sweden", countryId: "46", service: "ig" },
  { country: "Netherlands", countryId: "48", service: "ig" },
  { country: "Poland", countryId: "15", service: "ig" },
  { country: "Spain", countryId: "56", service: "ig" },
  { country: "Romania", countryId: "32", service: "ig" },
  { country: "Italy", countryId: "86", service: "ig" },
  { country: "Finland", countryId: "163", service: "ig" },
  { country: "Greece", countryId: "129", service: "ig" },
  { country: "Switzerland", countryId: "173", service: "ig" },

  // =========================
  // WhatsApp (wa)
  // =========================
  { country: "United States", countryId: "187", service: "wa" },
  { country: "Canada", countryId: "36", service: "wa" },
  { country: "Indonesia", countryId: "6", service: "wa" },
  { country: "Colombia", countryId: "33", service: "wa" },
  { country: "Vietnam", countryId: "10", service: "wa" },
  { country: "South Africa", countryId: "31", service: "wa" },
  { country: "Brazil", countryId: "73", service: "wa" },
  { country: "Philippines", countryId: "4", service: "wa" },
  { country: "United Kingdom", countryId: "16", service: "wa" },
  { country: "Malaysia", countryId: "7", service: "wa" },
  { country: "Australia", countryId: "175", service: "wa" },
  { country: "Netherlands", countryId: "48", service: "wa" },
  { country: "Germany", countryId: "43", service: "wa" },
  { country: "Chile", countryId: "151", service: "wa" },
  { country: "Sweden", countryId: "46", service: "wa" },
  { country: "Cameroon", countryId: "41", service: "wa" },
  { country: "Mexico", countryId: "54", service: "wa" },
  { country: "Thailand", countryId: "52", service: "wa" },
  { country: "Spain", countryId: "56", service: "wa" },
  { country: "France", countryId: "78", service: "wa" },
  { country: "Portugal", countryId: "117", service: "wa" },
  { country: "Romania", countryId: "32", service: "wa" },
  { country: "Ireland", countryId: "23", service: "wa" },
  { country: "Argentina", countryId: "39", service: "wa" },
  { country: "Poland", countryId: "15", service: "wa" },
  { country: "Italy", countryId: "86", service: "wa" },
  { country: "Denmark", countryId: "172", service: "wa" },
  { country: "Nigeria", countryId: "19", service: "wa" },
  { country: "Ivory Coast", countryId: "27", service: "wa" },
  { country: "Austria", countryId: "50", service: "wa" },
  { country: "Morocco", countryId: "37", service: "wa" },
  { country: "Kenya", countryId: "8", service: "wa" },
  { country: "Croatia", countryId: "45", service: "wa" },
  { country: "Finland", countryId: "163", service: "wa" },
  { country: "Egypt", countryId: "21", service: "wa" },
  { country: "Ghana", countryId: "38", service: "wa" },
  { country: "Congo", countryId: "150", service: "wa" },
  { country: "Czech Republic", countryId: "63", service: "wa" },
  { country: "Uruguay", countryId: "156", service: "wa" },
  { country: "Greece", countryId: "129", service: "wa" },
  { country: "Ukraine", countryId: "1", service: "wa" },
  { country: "New Zealand", countryId: "67", service: "wa" },
  { country: "Bulgaria", countryId: "83", service: "wa" },

  { country: "", countryId: "", service: "gf" },
  { country: "", countryId: "", service: "ght" },
  // =========================
  // Google / Gmail / YouTube (go)
  // =========================
  // ALL COUNTRIES ENABLED
  { country: "", countryId: "", service: "go" },
];

const extraServices = [
  { service: "tg", name: "Telegram" },
  { service: "fb", name: "Facebook" },
  { service: "wr", name: "Walmart" },
  { service: "gp", name: "Ticketmaster" }, 
  { service: "hb", name: "Twitch" },
  { service: "mc", name: "MiChat" },
  { service: "wx", name: "Apple" },
  { service: "mt", name: "Steam" },
  { service: "nu", name: "Stripe" }, 
  { service: "ng", name: "FunPay" }, 
  { service: "qg", name: "Money Pay / Monese" },
  { service: "vy", name: "Meta" },
  { service: "it", name: "Cash App" }, 
  { service: "yy", name: "Venmo" }, 
  { service: "bw", name: "Signal" },
  { service: "alj", name: "Spotify" },
  { service: "gc", name: "TradingView" },
  { service: "nc", name: "Payoneer" },
  { service: "zo", name: "Kaggle" },
  { service: "wb", name: "WeChat" },
  { service: "lf", name: "TikTok" },
  { service: "tw", name: "Twitter" },
  { service: "nf", name: "Netflix" },
  { service: "ts", name: "PayPal" },
  { service: "oi", name: "Tinder" },
  { service: "dh", name: "Ebay" },
];


const sharedCountries = nowService 
  .filter((item) => item.service === "ig")
  .map(({ country, countryId }) => ({
    country,
    countryId,
  }))

 const generatedServices = extraServices.flatMap((srv) =>
  sharedCountries.map((country) => ({
    country: country.country,
    countryId: country.countryId,
    service: srv.service,
  })),
);


export const services=[
  ...nowService,
  ...generatedServices
]



export const countries = [
  { country: "Afghanistan", countryId: 74 },
  { country: "Albania", countryId: 155 },
  { country: "Algeria", countryId: 58 },
  { country: "Angola", countryId: 76 },
  { country: "Anguilla", countryId: 181 },
  { country: "Antigua and Barbuda", countryId: 169 },
  { country: "Argentinas", countryId: 39 },
  { country: "Armenia", countryId: 148 },
  { country: "Aruba", countryId: 179 },
  { country: "Australia", countryId: 175 },
  { country: "Austria", countryId: 50 },
  { country: "Azerbaijan", countryId: 35 },
  { country: "Bahamas", countryId: 122 },
  { country: "Bahrain", countryId: 145 },
  { country: "Bangladesh", countryId: 60 },
  { country: "Barbados", countryId: 118 },
  { country: "Belarus", countryId: 51 },
  { country: "Belgium", countryId: 82 },
  { country: "Belize", countryId: 124 },
  { country: "Benin", countryId: 120 },
  { country: "Bermuda", countryId: 1003 },
  { country: "Bhutan", countryId: 158 },
  { country: "Bolivia", countryId: 92 },
  { country: "Bosnia and Herzegovina", countryId: 108 },
  { country: "Botswana", countryId: 123 },
  { country: "Brazil", countryId: 73 },
  { country: "Brunei Darussalam", countryId: 121 },
  { country: "Bulgaria", countryId: 83 },
  { country: "Burkina Faso", countryId: 152 },
  { country: "Burundi", countryId: 119 },
  { country: "CAF", countryId: 125 },
  { country: "Cambodia", countryId: 24 },
  { country: "Cameroon", countryId: 41 },
  { country: "Canada", countryId: 36 },
  { country: "Cape Verde", countryId: 186 },
  { country: "Cayman islands", countryId: 170 },
  { country: "Chad", countryId: 42 },
  { country: "Chile", countryId: 151 },
  { country: "China", countryId: 3 },
  { country: "Colombia", countryId: 33 },
  { country: "Comoros", countryId: 133 },
  { country: "Congo", countryId: 150 },
  { country: "Congo (Dem. Republic)", countryId: 18 },
  { country: "Costa Rica", countryId: 93 },
  { country: "Cote d`Ivoire Ivory Coast", countryId: 27 },
  { country: "Croatia", countryId: 45 },
  { country: "Cuba", countryId: 113 },
  { country: "Cyprus", countryId: 77 },
  { country: "Czech Republic", countryId: 63 },
  { country: "Denmark", countryId: 172 },
  { country: "Djibouti", countryId: 168 },
  { country: "Dominica", countryId: 126 },
  { country: "Dominican Republic", countryId: 109 },
  { country: "Ecuador", countryId: 105 },
  { country: "Egypt", countryId: 21 },
  { country: "El Salvador", countryId: 101 },
  { country: "Equatorial Guinea", countryId: 167 },
  { country: "Eritrea", countryId: 176 },
  { country: "Estonia", countryId: 34 },
  { country: "Ethiopia", countryId: 71 },
  { country: "Fiji", countryId: 189 },
  { country: "Finland", countryId: 163 },
  { country: "France", countryId: 78 },
  { country: "French Guiana", countryId: 162 },
  { country: "Gabon", countryId: 154 },
  { country: "Gambia", countryId: 28 },
  { country: "Georgia", countryId: 128 },
  { country: "Germany", countryId: 43 },
  { country: "Ghana", countryId: 38 },
  { country: "Gibraltar", countryId: 201 },
  { country: "Greece", countryId: 129 },
  { country: "Greenland", countryId: 1008 },
  { country: "Grenada", countryId: 127 },
  { country: "Guadeloupe", countryId: 160 },
  { country: "Guatemala", countryId: 94 },
  { country: "Guinea", countryId: 68 },
  { country: "Guinea-Bissau", countryId: 130 },
  { country: "Guyana", countryId: 131 },
  { country: "Haiti", countryId: 26 },
  { country: "Honduras", countryId: 88 },
  { country: "Hong Kong", countryId: 14 },
  { country: "Hungary", countryId: 84 },
  { country: "Iceland", countryId: 132 },
  { country: "India", countryId: 22 },
  { country: "Indonesia", countryId: 6 },
  { country: "Iran", countryId: 57 },
  { country: "Iraq", countryId: 47 },
  { country: "Ireland", countryId: 23 },
  { country: "Israel", countryId: 13 },
  { country: "Italy", countryId: 86 },
  { country: "Jamaica", countryId: 103 },
  { country: "Japan", countryId: 1001 },
  { country: "Jordan", countryId: 116 },
  { country: "Kazakhstan", countryId: 2 },
  { country: "Kenya", countryId: 8 },
  { country: "Korea", countryId: 1002 },
  { country: "Kosovo", countryId: 1004 },
  { country: "Kuwait", countryId: 100 },
  { country: "Kyrgyzstan", countryId: 11 },
  { country: "Lao People`s", countryId: 25 },
  { country: "Latvia", countryId: 49 },
  { country: "Lebanon", countryId: 153 },
  { country: "Lesotho", countryId: 136 },
  { country: "Liberia", countryId: 135 },
  { country: "Libya", countryId: 102 },
  { country: "Liechtenstein", countryId: 1005 },
  { country: "Lithuania", countryId: 44 },
  { country: "Luxembourg", countryId: 165 },
  { country: "Macau", countryId: 20 },
  { country: "Macedonia", countryId: 183 },
  { country: "Madagascar", countryId: 17 },
  { country: "Malawi", countryId: 137 },
  { country: "Malaysia", countryId: 7 },
  { country: "Maldives", countryId: 159 },
  { country: "Mali", countryId: 69 },
  { country: "Malta", countryId: 199 },
  { country: "Martinique", countryId: 1011 },
  { country: "Mauritania", countryId: 114 },
  { country: "Mauritius", countryId: 157 },
  { country: "Mexico", countryId: 54 },
  { country: "Moldova", countryId: 85 },
  { country: "Monaco", countryId: 144 },
  { country: "Mongolia", countryId: 72 },
  { country: "Montenegro", countryId: 171 },
  { country: "Montserrat", countryId: 180 },
  { country: "Morocco", countryId: 37 },
  { country: "Mozambique", countryId: 80 },
  { country: "Myanmar", countryId: 5 },
  { country: "Namibia", countryId: 138 },
  { country: "Nepal", countryId: 81 },
  { country: "Netherlands", countryId: 48 },
  { country: "New Caledonia", countryId: 185 },
  { country: "New Zealand", countryId: 67 },
  { country: "Nicaragua", countryId: 90 },
  { country: "Niger", countryId: 139 },
  { country: "Nigeria", countryId: 19 },
  { country: "Niue", countryId: 204 },
  { country: "Norway", countryId: 174 },
  { country: "Oman", countryId: 107 },
  { country: "Pakistan", countryId: 66 },
  { country: "Palestine", countryId: 188 },
  { country: "Panama", countryId: 112 },
  { country: "Papua new gvineya", countryId: 79 },
  { country: "Paraguay", countryId: 87 },
  { country: "Peru", countryId: 65 },
  { country: "Philippines", countryId: 4 },
  { country: "Poland", countryId: 15 },
  { country: "Portugal", countryId: 117 },
  { country: "Puerto Rico", countryId: 97 },
  { country: "Qatar", countryId: 111 },
  { country: "Reunion", countryId: 146 },
  { country: "Romania", countryId: 32 },
  { country: "Russian Federation", countryId: 0 },
  { country: "Rwanda", countryId: 140 },
  { country: "Saint Kitts and Nevis", countryId: 134 },
  { country: "Saint Lucia", countryId: 164 },
  { country: "Saint Vincent", countryId: 166 },
  { country: "Sao Tome and Principe", countryId: 178 },
  { country: "Saudi Arabia", countryId: 53 },
  { country: "Senegal", countryId: 61 },
  { country: "Serbia", countryId: 29 },
  { country: "Seychelles", countryId: 184 },
  { country: "Sierra Leone", countryId: 115 },
  { country: "Singapore", countryId: 196 },
  { country: "Sint Maarten", countryId: 1006 },
  { country: "Slovakia", countryId: 141 },
  { country: "Slovenia", countryId: 59 },
  { country: "Somalia", countryId: 149 },
  { country: "South Africa", countryId: 31 },
  { country: "South Sudan", countryId: 177 },
  { country: "Spain", countryId: 56 },
  { country: "Sri Lanka", countryId: 64 },
  { country: "Sudan", countryId: 1010 },
  { country: "Suriname", countryId: 142 },
  { country: "Swaziland", countryId: 106 },
  { country: "Sweden", countryId: 46 },
  { country: "Switzerland", countryId: 173 },
  { country: "Syria", countryId: 1333 },
  { country: "Taiwan", countryId: 55 },
  { country: "Tajikistan", countryId: 143 },
  { country: "Tanzania", countryId: 9 },
  { country: "Thailand", countryId: 52 },
  { country: "Timor-Leste", countryId: 91 },
  { country: "Togo", countryId: 99 },
  { country: "Trinidad and Tobago", countryId: 104 },
  { country: "Tunisia", countryId: 89 },
  { country: "Turkey", countryId: 62 },
  { country: "Turkmenistan", countryId: 161 },
  { country: "UAE", countryId: 95 },
  { country: "Uganda", countryId: 75 },
  { country: "Ukraine", countryId: 1 },
  { country: "United Kingdom", countryId: 16 },
  { country: "Uruguay", countryId: 156 },
  { country: "USA", countryId: 187 },
  { country: "USA (virtual)", countryId: 12 },
  { country: "Uzbekistan", countryId: 40 },
  { country: "Vanuatu", countryId: 1007 },
  { country: "Venezuela", countryId: 70 },
  { country: "Viet nam", countryId: 10 },
  { country: "Yemen", countryId: 30 },
  { country: "Zambia", countryId: 147 },
  { country: "Zimbabwe", countryId: 96 },
];