import { services as smsBowerServices } from "./neededCountries.js";

export const formatServiceName = (code) =>
  serviceNames[String(code || "").toLowerCase()] ||
  String(code || "Unknown").toUpperCase();

export const serviceNames = {
  // Core
  go: "Google/Gmail",
  ig: "Instagram / Threads",
  wa: "WhatsApp",
  tg: "Telegram",
  fb: "Facebook",
  tw: "Twitter / X",
  lf: "TikTok",
  ds: "Discord",
  rc: "Skype",
  wb: "WeChat",
  bw: "Signal",
  mc: "MiChat",
  vi: "Viber",
  im: "IMO",
  me: "LINE",
  fu: "Snapchat",
  hb: "Twitch",
  bl: "Bigo Live",
  ql: "QQ Live",
  vy: "Meta",
  gf: "Google Voice",
  ght: "Google Chat",

  // Dating
  oi: "Tinder",
  vm: "OkCupid",
  pf: "Plenty of Fish",
  wh: "TanTan",
  vz: "Hinge",
  yw: "Grindr",
  ako: "Her",
  tmi: "Taimi",
  ama: "WooPlus",
  ale: "Muzz",
  axr: "Match.com",

  // Finance / Wallet / Banking
  ts: "PayPal",
  nc: "Payoneer",
  ij: "Revolut",
  py: "Monese",
  hw: "AliPay",
  bo: "Wise",
  ahe: "Bunq",
  agh: "Bunq",
  qaf: "Cred",
  wfargo: "Wells Fargo",
  apr: "Capital One",
  ppl: "PYYPL",
  qjp: "Innopay",
  bbm: "TrueMoney",
  ael: "AstraPay",
  ajz: "LinkAja",
  qhy: "Omnicard",
  it: "Cash App",
  yy: "Venom",
  nu: "Stripe",
  ng: "FunPay",

  // Shopping / Ecommerce
  am: "Amazon",
  ab: "Alibaba",
  dh: "eBay",
  wr: "Walmart",
  ka: "Shopee",
  dl: "Lazada",
  xd: "Tokopedia",
  zp: "Pinduoduo",
  za: "Jingdong",
  Etsy: "Etsy",
  bgf: "Rapido",
  oz: "Poshmark",
  bsw: "Milanuncios",
  boo: "Kleinanzeigen",
  gp: "Ticketmaster",

  // Streaming / Entertainment
  nf: "Netflix",
  alj: "Spotify",
  wx: "Apple",
  mt: "Steam",
  aml: "Xbox",
  agz: "Ubisoft",
  ble: "NEXON",
  akr: "Sony LIV",
  aud: "Audible",

  // AI / Tech
  dr: "OpenAI / ChatGPT",
  acz: "Claude",
  grk: "Grok",
  pla: "PolloAI",
  aws: "AWS",
  dgo: "DigitalOcean",
  rap: "RapidAPI",
  ser: "SerpAPI",
  ama: "Vercel",
  git: "GitHub",
  crsr: "Cursor",

  // Delivery / Transport
  ub: "Uber",
  tx: "Bolt",
  gt: "Gett",

  // Communication
  tl: "Truecaller",
  xs: "GroupMe",
  tcw: "Switchere",
  apl: "Sideline",
  ari: "Ring4",

  // Crypto / Trading
  gc: "TradingView",
  apa: "Exness",
  sq: "KuCoinPlay",
  ald: "Paybis",
  ahm: "Bitrue",
  eec: "Neocrypto",

  // Gaming
  bz: "Blizzard",
  pon: "Pokemon",
  clg: "ClubGG",
  qld: "Ludo11",
  ggms: "Goa Games",

  // Food / Restaurants
  ip: "Burger King",
  fz: "KFC",
  ry: "McDonalds",
  aho: "Pizza Hut",
  cpt: "Chipotle",

  // Productivity / Work
  tn: "LinkedIn",
  abq: "Upwork",
  uns: "Unstop",
  foundit: "Foundit",
  aog: "Naukri",

  // Misc
  dp: "ProtonMail",
  mb: "Yahoo",
  pm: "AOL",
  qq: "Tencent QQ",
  zo: "Kaggle",
  qy: "Zhihu",
  kf: "Weibo",
  hk: "4FunLite",
  YoHo: "YoHo",
  fu: "Snapchat",
};

const provider2Services = [
  "Apple",
  "Cash App",
  "eBay",
  "Facebook",
  "FunPay",
  "Google Voice",
  "Google/Gmail",
  "Instagram / Threads",
  "WeChat",
  "Kaggle",
  "LinkedIn",
  "Meta",
  "MiChat",
  "Netflix",
  "Payoneer",
  "PayPal",
  "Signal",
  "Snapchat",
  "Spotify",
  "Steam",
  "Stripe",
  "Telegram",
  "Ticketmaster",
  "TikTok/Douyin",
  "Tinder",
  "TradingView",
  "Twitch",
  "Twitter / X",
  "Walmart",
  "WhatsApp",
];

const provider2ServiceAliases = {
  TikTok: "TikTok/Douyin",
};

export const filteredCountries = [
  "United States",
  "Mexico",
  "United Kingdom",
  "Netherlands",
  "Russia",
  "Latvia",
  "Sweden",
  "Portugal",
  "Estonia",
  "Romania",
  "Denmark",
  "Poland",
  "France",
  "Germany",
  "Ukraine",
  "Ireland",
  "Serbia",
  "Lithuania",
  "Croatia",
  "Austria",
  "Belarus",
  "Spain",
  "Slovenia",
  "Belgium",
  "Bulgaria",
  "Hungary",
  "Moldova",
  "Italy",
  "Greece",
  "Iceland",
  "Slovakia",
  "Monaco",
  "Albania",
  "Finland",
  "Luxembourg",
  "Montenegro",
  "Switzerland",
  "Norway",
  "Czech Republic",
  "Kazakhstan",
  "Indonesia",
  "Vietnam",
  "Philippines",
  "India",
  "Kyrgyzstan",
  "Malaysia",
  "Israel",
  "Cambodia",
  "Laos",
  "Yemen",
  "Uzbekistan",
  "Iraq",
  "Thailand",
  "Taiwan",
  "Bangladesh",
  "Turkey",
  "Pakistan",
  "Mongolia",
  "Afghanistan",
  "Cyprus",
  "Nepal",
  "Kuwait",
  "Oman",
  "Qatar",
  "Jordan",
  "Brunei",
  "Georgia",
  "Tajikistan",
  "Bahrain",
  "Armenia",
  "Lebanon",
  "Bhutan",
  "Maldives",
  "Turkmenistan",
  "Singapore",
  "Nigeria",
  "Kenya",
  "Tanzania",
  "Madagascar",
  "Egypt",
  "Gambia",
  "Morocco",
  "Ghana",
  "Cameroon",
  "Chad",
  "Algeria",
  "Senegal",
  "Guinea",
  "Mali",
  "Ethiopia",
  "Uganda",
  "Angola",
  "Mozambique",
  "Tunisia",
  "Zimbabwe",
  "Togo",
  "Swaziland",
  "Mauritania",
  "Burundi",
  "Benin",
  "Botswana",
  "Comoros",
  "Liberia",
  "Lesotho",
  "Malawi",
  "Namibia",
  "Niger",
  "Rwanda",
  "Zambia",
  "Somalia",
  "Gabon",
  "Mauritius",
  "Djibouti",
  "Eritrea",
  "Seychelles",
  "South Africa",
  "Haiti",
  "Colombia",
  "Argentina",
  "Peru",
  "Venezuela",
  "Brazil",
  "Paraguay",
  "Bolivia",
  "Ecuador",
  "Guyana",
  "Suriname",
  "Chile",
  "Uruguay",
  "Aruba",
  "Australia",
  "Fiji",
  "Honduras",
  "Nicaragua",
  "Guatemala",
  "Panama",
  "Belize",
  "Jamaica",
  "Barbados",
  "Bahamas",
  "Dominica",
  "Grenada",
  "Montserrat",
];

export const countryServices = filteredCountries.flatMap((country) =>
  Object.values(serviceNames).map((service) => ({
    country,
    service,
  })),
);

const provider2ServiceSet = new Set(provider2Services);

const provider2CountryServiceMap = new Map(
  smsBowerServices
    .flatMap((item) => {
      const smsBowerService = formatServiceName(item.service);
      const provider2Service =
        provider2ServiceAliases[smsBowerService] || smsBowerService;

      if (!provider2ServiceSet.has(provider2Service)) {
        return [];
      }

      const countries = item.country ? [item.country] : filteredCountries;

      return countries.map((country) => ({
        country,
        service: provider2Service,
      }));
    })
    .map((item) => [`${item.country}:${item.service}`, item]),
);

export const provider2CountryServices = [...provider2CountryServiceMap.values()];
