export const formatServiceName = (code) =>
  serviceNames[String(code || "").toLowerCase()] ||
  String(code || "Unknown").toUpperCase();

export const serviceNames = {
  // Core
  go: "Google / Gmail",
  ig: "Instagram",
  wa: "WhatsApp",
  tg: "Telegram",
  fb: "Facebook",
  tw: "Twitter / X",
  lf: "TikTok",
  ds: "Discord",
  rc: "Skype",
  wb: "WeChat",
  bw: "Signal",
  mc: "MiChat",
  vi: "Viber",
  im: "IMO",
  me: "LINE",
  fu: "Snapchat",
  hb: "Twitch",
  bl: "Bigo Live",
  ql: "QQ Live",
  vy: "Meta",
  gf: "Google Voice",
  ght: "Google Chat",

  // Dating
  oi: "Tinder",
  vm: "OkCupid",
  pf: "Plenty of Fish",
  wh: "TanTan",
  vz: "Hinge",
  yw: "Grindr",
  ako: "Her",
  tmi: "Taimi",
  ama: "WooPlus",
  ale: "Muzz",
  axr: "Match.com",

  // Finance / Wallet / Banking
  ts: "PayPal",
  nc: "Payoneer",
  ij: "Revolut",
  py: "Monese",
  hw: "AliPay",
  bo: "Wise",
  ahe: "Bunq",
  agh: "Bunq",
  qaf: "Cred",
  wfargo: "Wells Fargo",
  apr: "Capital One",
  ppl: "PYYPL",
  qjp: "Innopay",
  bbm: "TrueMoney",
  ael: "AstraPay",
  ajz: "LinkAja",
  qhy: "Omnicard",
  it: "Cash App",
  yy: "Venom",
  nu: "Stripe",
  ng: "FunPay",

  // Shopping / Ecommerce
  am: "Amazon",
  ab: "Alibaba",
  dh: "eBay",
  wr: "Walmart",
  ka: "Shopee",
  dl: "Lazada",
  xd: "Tokopedia",
  zp: "Pinduoduo",
  za: "Jingdong",
  Etsy: "Etsy",
  bgf: "Rapido",
  oz: "Poshmark",
  bsw: "Milanuncios",
  boo: "Kleinanzeigen",
  gp: "Ticketmaster",

  // Streaming / Entertainment
  nf: "Netflix",
  alj: "Spotify",
  wx: "Apple",
  mt: "Steam",
  aml: "Xbox",
  agz: "Ubisoft",
  ble: "NEXON",
  akr: "Sony LIV",
  aud: "Audible",

  // AI / Tech
  dr: "OpenAI / ChatGPT",
  acz: "Claude",
  grk: "Grok",
  pla: "PolloAI",
  aws: "AWS",
  dgo: "DigitalOcean",
  rap: "RapidAPI",
  ser: "SerpAPI",
  ama: "Vercel",
  git: "GitHub",
  crsr: "Cursor",

  // Delivery / Transport
  ub: "Uber",
  tx: "Bolt",
  gt: "Gett",
  xk: "DiDi",
  ls: "Careem",
  ul: "Getir",
  zk: "Deliveroo",
  nz: "Foodpanda",
  ni: "Gojek",

  // Communication
  tl: "Truecaller",
  xs: "GroupMe",
  tcw: "Switchere",
  talk: "Talkatone",
  ttn: "TextNow",
  apl: "Sideline",
  ari: "Ring4",

  // Crypto / Trading
  gc: "TradingView",
  apa: "Exness",
  sq: "KuCoinPlay",
  ald: "Paybis",
  ahm: "Bitrue",
  eec: "Neocrypto",

  // Gaming
  bz: "Blizzard",
  pon: "Pokemon",
  clg: "ClubGG",
  qld: "Ludo11",
  ggms: "Goa Games",

  // Food / Restaurants
  ip: "Burger King",
  fz: "KFC",
  ry: "McDonalds",
  aho: "Pizza Hut",
  cpt: "Chipotle",

  // Productivity / Work
  tn: "LinkedIn",
  abq: "Upwork",
  uns: "Unstop",
  foundit: "Foundit",
  aog: "Naukri",

  // Misc
  dp: "ProtonMail",
  mb: "Yahoo",
  pm: "AOL",
  qq: "Tencent QQ",
  zo: "Kaggle",
  qy: "Zhihu",
  kf: "Weibo",
  hk: "4FunLite",
  YoHo: "YoHo",
};
